"""empty message

Revision ID: 152cb4a83cb7
Revises: 2b54b23dec03
Create Date: 2019-09-07 22:52:49.652559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152cb4a83cb7'
down_revision = '2b54b23dec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='contacts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'contacts', ['phone'], unique=True)
    # ### end Alembic commands ###
