"""empty message

Revision ID: de8d1488ff93
Revises: 4bdd6c5025d2
Create Date: 2019-09-04 00:08:31.538470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8d1488ff93'
down_revision = '4bdd6c5025d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('address', sa.String(length=80), nullable=False))
    op.add_column('contacts', sa.Column('agenda_slug', sa.String(length=80), nullable=False))
    op.add_column('contacts', sa.Column('email', sa.String(length=80), nullable=False))
    op.add_column('contacts', sa.Column('full_name', sa.String(length=80), nullable=False))
    op.add_column('contacts', sa.Column('phone', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'contacts', ['phone'])
    op.create_unique_constraint(None, 'contacts', ['full_name'])
    op.create_unique_constraint(None, 'contacts', ['email'])
    op.create_unique_constraint(None, 'contacts', ['agenda_slug'])
    op.create_unique_constraint(None, 'contacts', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'phone')
    op.drop_column('contacts', 'full_name')
    op.drop_column('contacts', 'email')
    op.drop_column('contacts', 'agenda_slug')
    op.drop_column('contacts', 'address')
    # ### end Alembic commands ###
